=== AbhinavJain13/UMD-courses/LBSC690-Final-Project-Gallery/200709-archives/archives.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT archiveslisting (archives+)>
<!ELEMENT archives (parentinstitution, institution, address, address2, city, state, zip, website, opportunities, contact+)>

<!ATTLIST archives type (academic | government | military | museum | nonprofit | private | public) #REQUIRED>
<!ATTLIST email type2 (none | yes) #REQUIRED>

<!ELEMENT parentinstitution (#PCDATA)>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT address2 (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ELEMENT opportunities (#PCDATA)>
<!ELEMENT contact (prefix, firstname, middlename, lastname, suffix, title, phone, ext, fax, email)>
<!ELEMENT contact2 (prefix, firstname, middlename, lastname, suffix, title, phone, ext, fax, email)>

<!ELEMENT prefix (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT middlename (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT suffix (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT ext (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== AbhinavJain13/UMD-courses/LBSC690-Final-Project-Gallery/200709-archives/archives.xml
<?xml version="1.0"?>
<!DOCTYPE archiveslisting SYSTEM "archives.dtd">
<archiveslisting>
<archives type="public">
   <parentinstitution>Alexandria City Archives</parentinstitution>
   <institution>NA</institution>
   <address>801 S. Payne Street</address>
   <address2>NA</address2>
   <city>Alexandria</city>
   <state>VA</state>
   <zip>NA</zip>
   <website>NA</website>
   <opportunities>NA</opportunities>
   <contact>
      <prefix>NA</prefix>
      <firstname>Jackie</firstname>
      <middlename>NA</middlename>
      <lastname>Cohan</lastname>
      <suffix>NA</suffix>
      <title>NA</title>
      <phone>703.838.4591</phone>
      <ext>NA</ext>
      <fax>NA</fax>
      <email type2="none">NA</email>
      </contact>
</archives>
<archives type="public">
   <parentinstitution>Alexandria Library Special Collections</parentinstitution>
   <institution>NA</institution>
   <address>717 Queen Street</address>
   <address2>NA</address2>
   <city>Alexandria</city>
   <state>VA</state>
   <zip>22314</zip>
   <website>NA</website>
   <opportunities>NA</opportunities>
   <contact>
      <prefix>NA</prefix>
      <firstname>George</firstname>
      <middlename>K.</middlename>
      <lastname>Combs</lastname>
      <suffix>NA</suffix>
      <title>Archivist/Reference Librarian</title>
      <phone>703.838.4577</phone>
      <ext>213</ext>
      <fax>NA</fax>
      <email type2="yes">gcombs@alexandria.library.va.us</email>
   </contact>
</archives>
<archives type="nonprofit">
   <parentinstitution>American Association for the Advancement of Science Archives</parentinstitution>
   <institution>NA</institution>
   <address>1200 New York Avenue, N.W.</address>
   <address2>NA</address2>
   <city>Washington</city>
   <state>DC</state>
   <zip>20005</zip>
   <website>NA</website>
   <opportunities>NA</opportunities>
   <contact>
      <prefix>NA</prefix>
      <firstname>Amy</firstname>
      <middlename>NA</middlename>
      <lastname>Crumpton</lastname>
      <suffix>NA</suffix>
      <title>Archivist</title>
      <phone>202.326.6791</phone>
      <ext>NA</ext>
      <fax>NA</fax>
      <email type2="none">NA</email>
   </contact>
</archives>
<archives type="nonprofit">
   <parentinstitution>American Historical Association</parentinstitution>
   <institution>NA</institution>
   <address>400 A Street, NW</address>
   <address2>NA</address2>
   <city>Washington</city>
   <state>DC</state>
   <zip>20003-3889</zip>
   <website>NA</website>
   <opportunities>NA</opportunities>
   <contact>
      <prefix>NA</prefix>
      <firstname>Arnita</firstname>
      <middlename>NA</middlename>
      <lastname>Jones</lastname>
      <suffix>NA</suffix>
      <title>Executive Director</title>
      <phone>202.544.2422</phone>
      <ext>NA</ext>
      <fax>NA</fax>
      <email type2="none">NA</email>
   </contact>
</archives>
<archives type="private">
   <parentinstitution>American Institute of Architects</parentinstitution>
   <institution>AIA Archives</institution>
   <address>1735 New York Avenue, NW</address>
   <address2>NA</address2>
   <city>Washington</city>
   <state>DC</state>
   <zip>20006-5292</zip>
   <website>NA</website>
   <opportunities>NA</opportunities>
   <contact>
      <prefix>NA</prefix>
      <firstname>Sarah H.</firstname>
      <middlename>NA</middlename>
      <lastname>Turner</lastname>
      <suffix>NA</suffix>
      <title>Records Manager/Curator</title>
      <phone>202.626.7496</phone>
      <ext>NA</ext>
      <fax>202.626.7587</fax>
      <email type2="yes">turners@aiamail.aia.org</email>
   </contact>
</archives>
<archives type="nonprofit">
   <parentinstitution>American Institute for Conservation of Historic and Artistic Works</parentinstitution>
   <institution>NA</institution>
   <address>1717 K Street NW</address>
   <address2>NA</address2>
   <city>Washington</city>
   <state>DC</state>
   <zip>20006</zip>
   <website>NA</website>
   <opportunities>NA</opportunities>
   <contact>
      <prefix>NA</prefix>
      <firstname>Hilary</firstname>
      <middlename>NA</middlename>
      <lastname>Kaplan</lastname>
      <suffix>NA</suffix>
      <title>National Archives</title>
      <phone>301.837.0998</phone>
      <ext>NA</ext>
      <fax>NA</fax>
      <email type2="none">NA</email>
   </contact>
</archives>
<archives type="nonprofit">
   <parentinstitution>American Institute of Physics</parentinstitution>
   <institution>Center for the History of Physics / Neils Bohr Library and Archives</institution>
   <address>One Physics Ellipse</address>
   <address2>NA</address2>
   <city>College Park</city>
   <state>MD</state>
   <zip>20740</zip>
   <website>http://www.aip.org/history/</website>
   <opportunities>NA</opportunities>
   <contact>
      <prefix>NA</prefix>
      <firstname>Joseph</firstname>
      <middlename>NA</middlename>
      <lastname>Anderson</lastname>
      <suffix>NA</suffix>
      <title>Associate Director</title>
      <phone>301.209.3179</phone>
      <ext>NA</ext>
      <fax>301.209.0882</fax>
      <email type2="yes">rja@aip.org</email>
   </contact>
<!-- Deleted Contact 2 -->
</archives>
<archives type="private">
   <parentinstitution>American Psychological Association</parentinstitution>
   <institution>Archives and Library Services</institution>
   <address>750 First Street, NE</address>
   <address2>NA</address2>
   <city>Washington</city>
   <state>DC</state>
   <zip>20002-4242</zip>
   <website>NA</website>
   <opportunities>NA</opportunities>
   <contact>
      <prefix>NA</prefix>
      <firstname>Wade</firstname>
      <middlename>NA</middlename>
      <lastname>Pickren</lastname>
      <suffix>NA</suffix>
      <title>Director</title>
      <phone>202.336.5500</phone>
      <ext>NA</ext>
      <fax>NA</fax>
      <email type2="yes">wpickren@apa.org</email>
   </contact>
</archives>
<archives type="academic">
   <parentinstitution>American University</parentinstitution>
   <institution>Special Collections</institution>
   <address>4400 Massachusetts Avenue NW</address>
   <address2>NA</address2>
   <city>Washington</city>
   <state>DC</state>
   <zip>20016-8046</zip>
   <website>NA</website>
   <opportunities>NA</opportunities>
   <contact>
      <prefix>NA</prefix>
      <firstname>Susan</firstname>
      <middlename>NA</middlename>
      <lastname>McElrath</lastname>
      <suffix>NA</suffix>
      <title>University Archivist and Head of Special Collections</title>
      <phone>202.885.3255</phone>
      <ext>NA</ext>
      <fax>NA</fax>
      <email type2="yes">mcelrath@american.edu</email>
   </contact>
</archives>
<archives type="public">
   <parentinstitution>Arlington County Public Library</parentinstitution>
   <institution>Arlington County Archives Virginia Room</institution>
   <address>1015 N. Quincy Street</address>
   <address2>NA</address2>
   <city>Arlington</city>
   <state>VA</state>
   <zip>NA</zip>
   <website>NA</website>
   <opportunities>NA</opportunities>
   <contact>
      <prefix>NA</prefix>
      <firstname>Heather</firstname>
      <middlename>NA</middlename>
      <lastname>Crocetto</lastname>
      <suffix>NA</suffix>
      <title>NA</title>
      <phone>703.228.7724</phone>
      <ext>NA</ext>
      <fax>703.228.5692</fax>
      <email type2="yes">Hcrocetto@arlingtonva.us</email>
   </contact>
</archives>
<archives type="nonprofit">
   <parentinstitution>Association of American Medical Colleges</parentinstitution>
   <institution>Reference Center and Mary. H. Littlemeyer Archives</institution>
   <address>2450 N Street NW</address>
   <address2>NA</address2>
   <city>Washington</city>
   <state>DC</state>
   <zip>20037</zip>
   <website>http://www.aamc.org/about/history/archives.htm</website>
   <opportunities>NA</opportunities>
   <contact>
      <prefix>NA</prefix>
      <firstname>Molly</firstname>
      <middlename>NA</middlename>
      <lastname>Alexanfer</lastname>
      <suffix>NA</suffix>
      <title>Archivist</title>
      <phone>202.862.6261</phone>
      <ext>NA</ext>
      <fax>202.862.6136</fax>
      <email type2="yes">malexander@aamc.org</email>
   </contact>
</archives>
<archives type="museum">
   <parentinstitution>Banneker - Douglass Museum</parentinstitution>
   <institution>NA</institution>
   <address>84 Franklin St.</address>
   <address2>NA</address2>
   <city>Annapolis</city>
   <state>MD</state>
   <zip>21401</zip>
   <website>http://www.bdmuseum.com/</website>
   <opportunities>NA</opportunities>
   <contact>
      <prefix>NA</prefix>
      <firstname>Joni</firstname>
      <middlename>L.</middlename>
      <lastname>Jones</lastname>
      <suffix>Ph.D.</suffix>
      <title>Librarian - Archivist</title>
      <phone>410.216.6187</phone>
      <ext>NA</ext>
      <fax>410.974.2553</fax>
      <email type2="yes">JJones@mdp.state.md.us</email>
   </contact>
</archives>
<archives type="academic">
   <parentinstitution>Catholic University of America</parentinstitution>
   <institution>The American Catholic History Research Center and University Archives</institution>
   <address>101 Life Cycle Institute</address>
   <address2>NA</address2>
   <city>Washington</city>
   <state>DC</state>
   <zip>20064</zip>
   <website>NA</website>
   <opportunities>NA</opportunities>
   <contact>
      <prefix>NA</prefix>
      <firstname>John</firstname>
      <middlename>NA</middlename>
      <lastname>Shepherd</lastname>
      <suffix>NA</suffix>
      <title>Associate Archivist</title>
      <phone>202.319.5065</phone>
      <ext>NA</ext>
      <fax>NA</fax>
      <email type2="yes">shepherw@cua.edu</email>
   </contact>
</archives>
<archives type="military">
   <parentinstitution>Department of the Army</parentinstitution>
